stages:
    - compile
    - test
    - deploy

build:
  stage: compile
  script:
    - echo "Compiling..."

test:
  stage: test
  script:
    - echo "Testing..."

deploy-to-vm:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d --build