stages:
    - compile
    - test
    - deploy

build:
  stage: compile
  script:
    - echo "Compiling..."

frontend-test:
  stage: test
  script:
    - echo "Testing frontend..."

backend-test:
  stage: test
  script:
    - docker build -t backend-test-docker-image api/
    - docker run backend-test-docker-image pytest

deploy-to-vm:
  stage: deploy
  script:
    - echo "POSTGRES_DB=$PROD_POSTGRES_DB" >> .env
    - echo "POSTGRES_USER=$PROD_POSTGRES_USER" >> .env
    - echo "POSTGRES_PASSWORD=$PROD_POSTGRES_PASSWORD" >> .env
    - docker-compose down --remove-orphans
    - docker-compose up -d --build