services:
    api:
        build: ./api
        command: ["flask","run", "--host=0.0.0.0", "--port=5000"]
        volumes:
            - ./api:/api
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - FLASK_ENV=production
            - FLASK_APP=api.py
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - DATABASE_ADDRESS=database
            - SENDER_EMAIL=${SENDER_EMAIL}
            - SENDER_PASSWORD=${SENDER_PASSWORD}
        ports:
            - '5000:5000'
        networks:
            - frontend
            - backend
            
    client:
        build: ./client
        command: ["npm", "start"]
        volumes:
            - ./client:/client
            - node-modules:/client/node_modules
        environment:
            - NODE_ENV=production
        ports:
            - '3000:3000'
        depends_on:
            - api
        networks:
            - frontend
    
    database:
        image: postgres:11
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports: 
            - '5432:5432'
        volumes:
            - /var/lib/postgresql/data:/var/lib/postgresql/data
        networks:
            - backend

volumes:
    node-modules:
    data: {}

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge