services:
    api:
        build: ./api
        command: ["flask","run", "--host=0.0.0.0", "--port=5000"]
        volumes:
            - ./api:/api
        environment:
            - FLASK_ENV=development
            - FLASK_APP=api.py
            # - DB_CONNECTION_STRING=${PROD_DB_CONNECTION_STRING}
            - DB_CONNECTION_STRING='postgresql://postgres:postgres@database/drp_db'
        ports:
            - '5000:5000'
        networks:
            - frontend
            - backend
            
    client:
        build: ./client
        command: ["npm", "start"]
        volumes:
            - ./client:/client
            - node-modules:/client/node_modules
        environment:
            - NODE_ENV=development
        ports:
            - '3000:3000'
        depends_on:
            - api
        networks:
            - frontend
    
    database:
        image: postgres:11
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - '5432:5432'
        volumes:
            - /var/lib/postgresql/data:/var/lib/postgresql/data
        networks:
            - backend

volumes:
    node-modules:
    data: {}

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge